#!/Python27/python.exe
print "Content-type:text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<title align='center'>ADMIN</title>"
print "</head>"
print "<body>"
print "<center>"
print "<pre>"
print "<form name='login' action='second page.py' method='post'>"
print "ADMIN PAGE"
print "<table width='25%' height='20%' align='center' border='1' bgcolor='teak' cellspacing=0 cellpadding=0>"
print "<tr><td>USER NAME:</td><td><input type='text' name='username' required placeholder='username'></td></tr>"
print "<tr><td>PASSWORD:</td><td><input type='password' name='password' required placeholder='password'></td></tr>"
print "<tr><td></td><td><input type='submit' name='submit' value='login'></td></tr>"
print "</table>"
print "</form>"
print "</center>"
print "</body>"
print "</html>"
firstpage.py
Displaying fifthpage.py.