#!/Python27/python.exe
print "Content-type:text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<link rel='stylesheet' type='text/css' href='style.css'>"
print "</head>"
print "<body>"
print "<div id='wrapper'>"
print "<div id='banner'>"
print "<br><br>"
print "<br><br>"
print "<center><b><font size=5>REGISTRATION PAGE</font></b>"
print "</div>"
print "<div id='topmenu'><center><a href='fifth1.py'>VIEW DETAILS</a></center></div>"
print "<div id='columnleft'></div>"
print "<div id='columnright'></div>"
print "<div id='columncenter'>"
print "<br><br>"
print "<form name='login' action='fourth.py' method='get'>"
print "<center><table width='25%' height='20%' align='center' border='0' bgcolor='teal' cellspacing=1 cellpadding=1>"
print "<tr><td>STAFFID:</td><td><input type='text' name='sid' required placeholder='staffid'></td></tr>"
print "<tr><td>NAME:</td><td><input type='text' name='sname' required placeholder='staffname'></td></tr>"
print "<tr><td>DEPARTMENT:</td><td><input type='text' name='dept' required placeholder='department'></td></tr>"
print "<tr><td>EMAIL ID:</td><td><input type='email' name='eid' required placeholder='example@gmail.com'></td></tr>"
print "<tr><td>PHONE NO:</td><td><input type='text' name='pno' required placeholder='phoneno'></td></tr>"
print "</table>"
print "<br><br>"
print "<center><input type='submit' name='submit' value='REGISTER'>"
print "</form></div>"
print "<div id='footer'>"
print "</div>"
print "</div>"
print "</body>"
print "</html>"